Salesforce/src/objects/Automated_Process_Deactivation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Switch settings to allow custom automated processes to be disabled per profile</description>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>Name(s) of the automated process affected by the setting. Multiple processes can be entered, delimit with a semi-colon</description>
        <inlineHelpText>Multiple processes can be entered, delimit with a semi-colon</inlineHelpText>
        <label>Process Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Setting_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true to deactivate the custom automated processes listed for the user/profile</description>
        <inlineHelpText>Set to checked to deactivate the custom automated processes listed for the user/profile</inlineHelpText>
        <label>Setting Activated</label>
        <type>Checkbox</type>
    </fields>
    <label>Automated Process Deactivation</label>
</CustomObject>

Salesforce/src/objects/Trigger_Deactivation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trigger switches so that triggers can be disabled per profile</description>
    <fields>
        <fullName>Setting_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true to deactivate the triggers listed for the user/profile</description>
        <label>Setting Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trigger_Names__c</fullName>
        <description>Name(s) of the trigger affected by the setting. Multiple triggers can be entered, delimit with a semi-colon</description>
        <inlineHelpText>Apex Trigger name. Multiple triggers can be entered, delimit with a semi-colon</inlineHelpText>
        <label>Trigger Names</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Trigger Deactivation</label>
</CustomObject>

Salesforce/src/classes/utl_User.cls
public class utl_User 
{
    public Static Trigger_Deactivation__c td
    {
        get
        {
            if(td == null)
            {
                td = Trigger_Deactivation__c.getInstance();
                
                if(td != null && td.Id == null)
                   td = null;
            }
            return td;
        }
        set;
    }
        
    public static Boolean isTriggerDeactivationEnabledForAllTriggers
    {
        get
        {
            if(isTriggerDeactivationEnabledForAllTriggers == null)
                isTriggerDeactivationEnabledForAllTriggers = false;
            return isTriggerDeactivationEnabledForAllTriggers;
        }
        set;
    }
    
    public static Boolean isProcessEnabledForMe(String processName)
    {
        Automated_Process_Deactivation__c apd = Automated_Process_Deactivation__c.getInstance();
        //always active if no specific setting is available
        if(apd.Id == null)
            return true;
        
        return !(apd.Setting_Activated__c && apd.Process_Name__c.contains(processName));
    }
    
    public static  Boolean isTriggerActiveForMe(String triggerName)
    {
        if(isTriggerDeactivationEnabledForAllTriggers) return false;
        
        if(td == null) return true;
          
        return (!(td.Setting_Activated__c && td.Trigger_Names__c.contains(triggerName))); 
    }
}